apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: schcsaba/kub-demo-tasks:latest
        volumeMounts:
          - mountPath: /app/tasks
            name: tasks-volume
        env:
          - name: AUTH_ADDRESS
            value: "auth-service.default"
          - name: TASKS_FOLDER
            value: tasks
      volumes:
        - name: tasks-volume
          hostPath:
            path: /tasks
            type: DirectoryOrCreate